import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/unenv/runtime/polyfill/fetch.node.mjs';
export { l as localFetch } from './chunks/nitro/nitro-prerenderer.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/h3/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/ohmyfetch/dist/node.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/destr/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/radix3/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/unenv/runtime/fetch/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/hookable/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/scule/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/defu/dist/defu.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/ohash/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/unstorage/dist/index.mjs';
import 'file:///Users/robletts/Dev/projects/personal-site/node_modules/ufo/dist/index.mjs';
