// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'LinkWrapper': typeof import("../components/LinkWrapper.vue")['default'],
    'MainContent': typeof import("../components/MainContent.vue")['default'],
    'SiteHeader': typeof import("../components/SiteHeader.vue")['default'],
    'ThemeToggle': typeof import("../components/ThemeToggle.vue")['default'],
    'SVGDocument': typeof import("../components/SVG/Document.vue")['default'],
    'SVGGitHub': typeof import("../components/SVG/GitHub.vue")['default'],
    'SVGLetterboxd': typeof import("../components/SVG/Letterboxd.vue")['default'],
    'SVGLinkedIn': typeof import("../components/SVG/LinkedIn.vue")['default'],
    'SVGMail': typeof import("../components/SVG/Mail.vue")['default'],
    'SVGMoon': typeof import("../components/SVG/Moon.vue")['default'],
    'SVGSun': typeof import("../components/SVG/Sun.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyLinkWrapper': typeof import("../components/LinkWrapper.vue")['default'],
    'LazyMainContent': typeof import("../components/MainContent.vue")['default'],
    'LazySiteHeader': typeof import("../components/SiteHeader.vue")['default'],
    'LazyThemeToggle': typeof import("../components/ThemeToggle.vue")['default'],
    'LazySVGDocument': typeof import("../components/SVG/Document.vue")['default'],
    'LazySVGGitHub': typeof import("../components/SVG/GitHub.vue")['default'],
    'LazySVGLetterboxd': typeof import("../components/SVG/Letterboxd.vue")['default'],
    'LazySVGLinkedIn': typeof import("../components/SVG/LinkedIn.vue")['default'],
    'LazySVGMail': typeof import("../components/SVG/Mail.vue")['default'],
    'LazySVGMoon': typeof import("../components/SVG/Moon.vue")['default'],
    'LazySVGSun': typeof import("../components/SVG/Sun.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const LinkWrapper: typeof import("../components/LinkWrapper.vue")['default']
export const MainContent: typeof import("../components/MainContent.vue")['default']
export const SiteHeader: typeof import("../components/SiteHeader.vue")['default']
export const ThemeToggle: typeof import("../components/ThemeToggle.vue")['default']
export const SVGDocument: typeof import("../components/SVG/Document.vue")['default']
export const SVGGitHub: typeof import("../components/SVG/GitHub.vue")['default']
export const SVGLetterboxd: typeof import("../components/SVG/Letterboxd.vue")['default']
export const SVGLinkedIn: typeof import("../components/SVG/LinkedIn.vue")['default']
export const SVGMail: typeof import("../components/SVG/Mail.vue")['default']
export const SVGMoon: typeof import("../components/SVG/Moon.vue")['default']
export const SVGSun: typeof import("../components/SVG/Sun.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyLinkWrapper: typeof import("../components/LinkWrapper.vue")['default']
export const LazyMainContent: typeof import("../components/MainContent.vue")['default']
export const LazySiteHeader: typeof import("../components/SiteHeader.vue")['default']
export const LazyThemeToggle: typeof import("../components/ThemeToggle.vue")['default']
export const LazySVGDocument: typeof import("../components/SVG/Document.vue")['default']
export const LazySVGGitHub: typeof import("../components/SVG/GitHub.vue")['default']
export const LazySVGLetterboxd: typeof import("../components/SVG/Letterboxd.vue")['default']
export const LazySVGLinkedIn: typeof import("../components/SVG/LinkedIn.vue")['default']
export const LazySVGMail: typeof import("../components/SVG/Mail.vue")['default']
export const LazySVGMoon: typeof import("../components/SVG/Moon.vue")['default']
export const LazySVGSun: typeof import("../components/SVG/Sun.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
